    nodes = [
        Node(
            package="llm_agent",
            executable="llm_agent_node",
            name="llm_agent",
            output="screen",
        ),
        Node(
            package="shot_planner",
            executable="shot_planner_node",
            name="shot_planner",
            output="screen",
        ),
        Node(
            package="vision_tracker",
            executable="vision_tracker_node",
            name="vision_tracker",
            output="screen",
        ),
        Node(
            package="snydrone_camera",
            executable="camera_stub_node",
            name="camera_stub",
            output="screen",
        ),
        Node(
            package="traj_follower",
            executable="traj_follower_node",
            name="traj_follower",
            output="screen",
        ),
        Node(
            package="dataset_logger",
            executable="dataset_logger_node",
            name="dataset_logger",
            output="screen",
        ),
    ]
